In [26]:
import sys
sys.path.insert(0, '/home/hana/Downloads/code_example0613/PINNs-master/Utilities/')

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import scipy.io
from scipy.interpolate import griddata
from pyDOE import lhs
from plotting import newfig, savefig
from mpl_toolkits.mplot3d import Axes3D
import time
import matplotlib.gridspec as gridspec
from mpl_toolkits.axes_grid1 import make_axes_locatable



a1= np.random.seed(1234)
a2 = tf.set_random_seed(1234)

In [29]:
x0 = np.array([[1,3],[2,4], [4,5]])
X0 = np.concatenate((x0, 0*x0), 1) # (x0, 0)
print(X0)
X0 = np.concatenate((X0, 0*x0), 1) # (x0, 0)
print(X0)



[[1 3 0 0]
 [2 4 0 0]
 [4 5 0 0]]
[[1 3 0 0 0 0]
 [2 4 0 0 0 0]
 [4 5 0 0 0 0]]
